apiVersion: skaffold/v4beta9
kind: Config
metadata: 
  name: deploy-run-files
profiles:
- name: run_uat
  manifests:
    rawYaml:
    - run_uat.yaml
- name: run_prod
  manifests:
    rawYaml:
    - run_prod.yaml
deploy:
  cloudrun: {}