name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install Flask-Testing
          cd service
          pip install -r requirements.txt
      - name: Test
        run: |
          cd service
          python test_app.py

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          cd service
          docker build -t mkruzic/rounds_challenge:$GITHUB_RUN_ID .
          docker push mkruzic/rounds_challenge:$GITHUB_RUN_ID

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      APP: 'rounds-challenge'
      REGION: 'us-central1'
      PROJECT_ID: 'rounds-challenge'
      GAR_LOCATION: 'us-central1'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.CODE_DEPLOY_CREDS }}'
      - name: 'Create release name'
        run: |-
          echo "RELEASE_NAME=${{ env.APP }}-${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
      - name: 'Create Cloud Deploy release'
        uses: 'google-github-actions/create-cloud-deploy-release@v0'
        with:
          delivery_pipeline: 'files-app-prod'
          name: '${{ env.RELEASE_NAME }}'
          region: '${{ env.REGION }}'
          description: '${{ env.GITHUB_COMMIT_MSG }}'
          skaffold_file: 'service/skaffold.yaml'
          images: 'service=${{ env.GAR_LOCATION }}-docker.pkg.dev/mkruzic/rounds_challenge/${{ env.GITHUB_RUN_ID }}'